-- CreateEnum
CREATE TYPE "PulseStatus" AS ENUM ('SAFE', 'SAFE_BUT_SITUATION_ONGOING', 'IN_DANGER', 'IN_SERIOUS_DANGER', 'PROPERTY_LOSS', 'INJURED', 'NEED_MEDICAL_ASSISTANCE', 'SERIOUSLY_INJURED');

-- AlterTable
ALTER TABLE "Pulse" ADD COLUMN     "message" TEXT,
ADD COLUMN     "reachable" BOOLEAN,
ADD COLUMN     "status" "PulseStatus" NOT NULL DEFAULT 'SAFE';
